#!/bin/bash
#diff -y --suppress-common-lines "$@" | grep -v '<$' | grep --color=always 'CONFIG_[-A-Za-z0-9_]\+'

colorme() {
	local value color
	value="$1"
	case "$value" in
		m)    color=6 ;;
		y)    color=2 ;;
		n)    color=1 ;;
		_|"") color=1 ;;
		*)    color=4 ;;
	esac
	printf "\033[1;3${color}m${value:-_}\033[0m"
}

IFS='|'
while read left right; do
	if [ ! "$right" ]; then
		if [ ! "${left%%>*}" ]; then
			right="${left#>}"
			unset left
		fi
	fi
	config="${left%=*}"
	[ ! "$config" ] && config="${right%=*}"
	leftvalue="$(colorme "${left##*=}")"
	rightvalue="$(colorme "${right##*=}")"
	printf "%-35s $leftvalue -> $rightvalue\n" "$config"
done << _EOF
$(diff -y --suppress-common-lines "$@" | grep -v '<$' | sed "s/[[:space:]]//g; s/#\(.*\)isnotset/\1=_/g;")
_EOF

exit 0
