#!/bin/bash

LISTNAME='patch_list'

main() {
	local IFS
	recurse "$@"
}

parse_list() {
	local IFS i patch newname
	i=0
	while read patch; do
	    [[ $patch ]] || continue
    	echo "$patch" | grep -q '^#' && continue
    	[[ -f $patch ]] || continue
		mkdir -p listed
		newname="${patch////-}"
		while true; do
			case "$newname" in
				*.patch) newname="${newname%*.patch}" ;;
				*.diff)  newname="${newname%*.diff}"  ;;
				*) break ;;
			esac
		done
		newname="${newname}.patch"
    	i=$((i+1))
    	mv "$patch" "listed/$(printf '%03d-%s' $i "$newname")"
		printf '.'
	done < $LISTNAME

	printf '\n%d patches moved to listed/\n' $i
	[[ -d listed ]] || return
	cd listed
	ls -1 *.patch > $LISTNAME
	cd ..
}

recurse() {
	local IFS root dir
	root="$1"
	cd "${root:-.}"
	while read dir; do
		[[ "$dir" ]] || continue
		[[ "$dir" = "listed" ]] && continue
		echo "now: $dir"
		[[ -f "$dir/$LISTNAME" ]] || continue
		cd "$dir"
		parse_list
		cd ..
	done <<< "$(find -maxdepth 1 -type d ! -name '.')"
	[[ -f "$LISTNAME" ]] && parse_list

}

#main "$@"
recurse "$@"
exit $?
