#!/bin/bash
# psgrep: greps ps output for processes by name patterns


# internals
DOLLAR_ZERO="$0"
SHORT_NAME="${0##*/}"


# functions
show_usage() {
	printf -- 'usage: %s [pattern]\n' "$SHORT_NAME"
	exit 0
}

say() {
	[[ $# -gt 0 ]] || err NUM_ARGS say $# more
	local IFS msg

	case "$1" in
		ERR_NO_MATCHES) msg='no matches for pattern "%s"' ;;
		ERR_NUM_ARGS)   msg='internal error! function %s received %d arguments, expected %s' ;;
		ERR_|"") msg='empty message :(' ;; # drop down
		*)	msg="$*"
			shift $#
			;;
	esac

	shift 2>&1
	printf -- "[%s] $msg\n" "$SHORT_NAME" "$@"
}

err() {
	local IFS first
	first="ERR_$1"

	shift 2>&1
	say "$first" "$@"

	exit 1
}

main() {
	[[ $# -gt 0 ]] || show_usage
	local IFS LC_ALL all escaped buf

	all="$(ps axo user,pid,cmd)"
	buf="$(echo "$all" | grep -- "^[^ ]\+ \+[0-9]\+ .*$*" 2>/dev/null | grep -v -- "^[^ ]\+ \+[0-9]\+ $SHELL $0 $*")"
	[[ $? -eq 0 ]] || err NO_MATCHES "$*"

	echo "$all" | head -n1  # banner
	echo "$buf" | grep --color=always -- "$*"  # for colors

	return 0
}

# execution start

main "$@"
exit $?
