#!/bin/bash

delta=
removed=
pass=
IFS=$'\n'

[[ "$1" = '-f' ]] || printf -- 'dry run; -f to force\n'

while [[ ${delta:-1} -gt 0 ]]; do
	delta=0
	for dir in $(find -type d ! -name '.'); do
		[[ $(ls -A1 "$dir" 2>&1 | wc -l) -gt 0 ]] && continue
		[[ "$1" = '-f' ]] && rmdir -v "$dir" || printf -- 'rmdir -v "%s"\n' "$dir"
		removed=$((removed+1))
		delta=$((delta+1))
	done
	[[ $delta -gt 0 ]] && pass=$((pass+1))
	[[ "$1" = '-f' ]] || break
done

printf "%d directories removed. (%d passes)\n" ${removed:-0} $pass
